
name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2.3.1
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.3
        with:
          version: 1.0.9
          create_virtualenvs: true
      - name: Cache
        id: cache
        uses: actions/cache@v2.0.0
        with:
          path: ~/.virtualenvs
          key: poetry-venv-${{ hashFiles('poetry.lock') }}
      - name: Set Poetry config
        run: |
          poetry config settings.virtualenvs.in-project false
          poetry config settings.virtualenvs.path ~/.virtualenvs
      - name: Install Dependencies via Poetry
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Run mypy
        run: poetry run mypy .
      - name: Run black
        run: poetry run black . --check
